packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@nestjs/core': true
  '@parcel/watcher': set this to true or false
  '@prisma/client': false
  '@prisma/engines': true
  '@swc/core': set this to true or false
  bcrypt: false
  msgpackr-extract: true
  msw: set this to true or false
  prisma: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - 'prisma'
  - 'sharp'
  - 'unrs-resolver'
  - 'bcrypt'
  - 'msw'
  - '@parcel/watcher'
  - '@swc/core'
